/**
 * 100 ta Intermediate (B1–B2) vocabulary — test bazasi.
 *
 * Har bir yozuv savol generatoriga yetarli ma'lumot beradi:
 *  · `meaning`    — o'zbekcha ma'no (EN→UZ savollarida javob/chalg'ituvchi).
 *  · `definition` — qisqa inglizcha izoh (kontekst savollarida variant).
 *  · `pos`        — chalg'ituvchilarni bir xil turkumdan tanlash uchun.
 *  · `examples`   — HAR BIRI so'zning o'zini yoki `forms` dagi shaklini
 *                   o'z ichiga oladi; bo'sh joy to'ldirish savoli shundan
 *                   yasaladi. Bu shart testda tekshiriladi.
 */

export type Pos = "noun" | "verb" | "adjective" | "adverb" | "linker";

export type VocabWord = {
  word: string;
  meaning: string;
  definition: string;
  pos: Pos;
  level: "B1" | "B2";
  examples: string[];
  synonyms: string[];
  /** Gaplarda uchraydigan qo'shimcha shakllar (fe'l zamonlari, ko'plik). */
  forms?: string[];
};

export const WORDS: VocabWord[] = [
  {
    word: "routine",
    meaning: "kundalik tartib",
    definition: "a fixed set of things you do regularly",
    pos: "noun",
    level: "B1",
    examples: [
      "My morning routine starts with a cup of coffee and ten minutes of reading.",
      "Checking the machines is part of the daily routine at the factory.",
    ],
    synonyms: ["regular schedule"],
    forms: ["routines"],
  },
  {
    word: "habit",
    meaning: "odat",
    definition: "something you do often, almost without thinking",
    pos: "noun",
    level: "B1",
    examples: [
      "Reading before bed is a good habit that helps me sleep.",
      "He is trying to break the habit of checking his phone at night.",
    ],
    synonyms: ["custom"],
    forms: ["habits"],
  },
  {
    word: "hobby",
    meaning: "sevimli mashg'ulot",
    definition: "an activity you do for pleasure in your free time",
    pos: "noun",
    level: "B1",
    examples: [
      "Photography has been my hobby since I was a child.",
      "She turned her hobby into a small but profitable business.",
    ],
    synonyms: ["pastime"],
    forms: ["hobbies"],
  },
  {
    word: "experience",
    meaning: "tajriba",
    definition: "knowledge or skill you get from doing something",
    pos: "noun",
    level: "B1",
    examples: [
      "She has five years of experience in digital marketing.",
      "Living abroad for a year was a valuable experience for me.",
    ],
    synonyms: ["practical knowledge"],
    forms: ["experiences", "experienced"],
  },
  {
    word: "prefer",
    meaning: "afzal ko'rmoq",
    definition: "to like one thing more than another",
    pos: "verb",
    level: "B1",
    examples: [
      "I prefer tea to coffee in the morning.",
      "Most students prefer studying in a quiet room.",
    ],
    synonyms: ["like better"],
    forms: ["prefers", "preferred", "preferring"],
  },
  {
    word: "enjoy",
    meaning: "zavq olmoq",
    definition: "to get pleasure from something",
    pos: "verb",
    level: "B1",
    examples: [
      "I really enjoy walking in the park after a long working day.",
      "They enjoyed the concert even though it rained all evening.",
    ],
    synonyms: ["take pleasure in"],
    forms: ["enjoys", "enjoyed", "enjoying"],
  },
  {
    word: "spend",
    meaning: "sarflamoq",
    definition: "to use time or money for something",
    pos: "verb",
    level: "B1",
    examples: [
      "I spend two hours a day learning English.",
      "He spent all of his savings on a second-hand car.",
    ],
    synonyms: ["use up"],
    forms: ["spends", "spent", "spending"],
  },
  {
    word: "usually",
    meaning: "odatda",
    definition: "in most cases, as a normal rule",
    pos: "adverb",
    level: "B1",
    examples: [
      "I usually wake up at seven o'clock, even at the weekend.",
      "We usually meet on Fridays to discuss the project.",
    ],
    synonyms: ["normally"],
  },
  {
    word: "especially",
    meaning: "ayniqsa",
    definition: "more than usual, above all",
    pos: "adverb",
    level: "B1",
    examples: [
      "I love fruit, especially mangoes and fresh grapes.",
      "The city is beautiful, especially in early autumn.",
    ],
    synonyms: ["particularly"],
  },
  {
    word: "recently",
    meaning: "yaqinda",
    definition: "a short time ago",
    pos: "adverb",
    level: "B1",
    examples: [
      "I have recently started a new job in a small company.",
      "They moved to a bigger flat quite recently.",
    ],
    synonyms: ["lately"],
  },
  {
    word: "relationship",
    meaning: "munosabat",
    definition: "the way two people or groups behave towards each other",
    pos: "noun",
    level: "B1",
    examples: [
      "A good relationship is built on honesty and patience.",
      "The two countries have a strong trade relationship.",
    ],
    synonyms: ["connection"],
    forms: ["relationships"],
  },
  {
    word: "friendship",
    meaning: "do'stlik",
    definition: "the close feeling between friends",
    pos: "noun",
    level: "B1",
    examples: [
      "Their friendship has lasted for more than twenty years.",
      "True friendship survives long distances and busy lives.",
    ],
    synonyms: ["companionship"],
    forms: ["friendships"],
  },
  {
    word: "trust",
    meaning: "ishonmoq, ishonch",
    definition: "to believe that someone is honest and will not harm you",
    pos: "verb",
    level: "B1",
    examples: [
      "I trust her completely, so she keeps the keys to the office.",
      "It takes years to build trust and only seconds to lose it.",
    ],
    synonyms: ["rely on"],
    forms: ["trusts", "trusted", "trusting"],
  },
  {
    word: "support",
    meaning: "qo'llab-quvvatlamoq",
    definition: "to help someone or agree with their plan",
    pos: "verb",
    level: "B1",
    examples: [
      "My parents always support my decisions, even the risky ones.",
      "The charity supports families who cannot pay for medicine.",
    ],
    synonyms: ["back up"],
    forms: ["supports", "supported", "supporting"],
  },
  {
    word: "respect",
    meaning: "hurmat qilmoq, hurmat",
    definition: "to admire someone and treat them politely",
    pos: "verb",
    level: "B1",
    examples: [
      "I respect people who admit their mistakes openly.",
      "She quickly earned the respect of her new colleagues.",
    ],
    synonyms: ["look up to"],
    forms: ["respects", "respected", "respecting"],
  },
  {
    word: "honest",
    meaning: "halol, rostgo'y",
    definition: "always telling the truth and not cheating",
    pos: "adjective",
    level: "B1",
    examples: [
      "Please give me an honest answer, even if it hurts.",
      "He is too honest to lie about a mistake like that.",
    ],
    synonyms: ["truthful"],
  },
  {
    word: "reliable",
    meaning: "ishonchli",
    definition: "someone or something you can depend on",
    pos: "adjective",
    level: "B1",
    examples: [
      "Sarah is very reliable, so I always trust her with important tasks.",
      "We need a reliable car for these long winter journeys.",
    ],
    synonyms: ["trustworthy", "dependable"],
  },
  {
    word: "patient",
    meaning: "sabrli",
    definition: "able to wait calmly without getting angry",
    pos: "adjective",
    level: "B1",
    examples: [
      "A good teacher must be patient with slower learners.",
      "Be patient — the results of daily practice come later.",
    ],
    synonyms: ["calm"],
  },
  {
    word: "confident",
    meaning: "o'ziga ishonchli",
    definition: "sure about your own ability",
    pos: "adjective",
    level: "B1",
    examples: [
      "After months of practice, she felt confident speaking English.",
      "He is confident that the plan will work this time.",
    ],
    synonyms: ["self-assured"],
  },
  {
    word: "responsible",
    meaning: "mas'uliyatli",
    definition: "having a duty to deal with something, or behaving sensibly",
    pos: "adjective",
    level: "B1",
    examples: [
      "She is responsible for the whole marketing department.",
      "He is a responsible driver who never breaks the speed limit.",
    ],
    synonyms: ["accountable"],
  },
  {
    word: "education",
    meaning: "ta'lim",
    definition: "the process of teaching and learning at school",
    pos: "noun",
    level: "B1",
    examples: [
      "Education opens doors to better jobs and better pay.",
      "The government spends a large part of the budget on education.",
    ],
    synonyms: ["schooling"],
  },
  {
    word: "knowledge",
    meaning: "bilim",
    definition: "the information and understanding you have about something",
    pos: "noun",
    level: "B1",
    examples: [
      "His knowledge of local history is genuinely impressive.",
      "Knowledge without regular practice is quickly forgotten.",
    ],
    synonyms: ["understanding"],
  },
  {
    word: "subject",
    meaning: "fan, mavzu",
    definition: "an area of study, or the topic being discussed",
    pos: "noun",
    level: "B1",
    examples: [
      "Maths was always my favourite subject at school.",
      "Let's change the subject before the argument gets worse.",
    ],
    synonyms: ["topic"],
    forms: ["subjects"],
  },
  {
    word: "assignment",
    meaning: "topshiriq",
    definition: "a piece of work given to a student or worker",
    pos: "noun",
    level: "B1",
    examples: [
      "The teacher gave us a difficult assignment about climate change.",
      "I finished my assignment just an hour before the deadline.",
    ],
    synonyms: ["task"],
    forms: ["assignments"],
  },
  {
    word: "skill",
    meaning: "mahorat, ko'nikma",
    definition: "the ability to do something well because you learned it",
    pos: "noun",
    level: "B1",
    examples: [
      "Clear communication is an important skill in every office.",
      "She has excellent problem-solving skills and works fast.",
    ],
    synonyms: ["ability"],
    forms: ["skills"],
  },
  {
    word: "improve",
    meaning: "yaxshilamoq",
    definition: "to make something better, or to get better",
    pos: "verb",
    level: "B1",
    examples: [
      "I have been studying English for two years and my speaking has improved a lot.",
      "Reading every day will improve your vocabulary faster than anything else.",
    ],
    synonyms: ["get better"],
    forms: ["improves", "improved", "improving"],
  },
  {
    word: "practice",
    meaning: "mashq qilmoq, mashq",
    definition: "to do something repeatedly in order to get better at it",
    pos: "verb",
    level: "B1",
    examples: [
      "You need to practice speaking every single day.",
      "She practised the presentation three times before the meeting.",
    ],
    synonyms: ["train", "rehearse"],
    forms: ["practices", "practiced", "practicing", "practises", "practised", "practising"],
  },
  {
    word: "concentrate",
    meaning: "diqqatni jamlamoq",
    definition: "to give all your attention to one thing",
    pos: "verb",
    level: "B1",
    examples: [
      "I can't concentrate when the television is on in the next room.",
      "Try to concentrate on one task at a time.",
    ],
    synonyms: ["pay close attention"],
    forms: ["concentrates", "concentrated", "concentrating"],
  },
  {
    word: "graduate",
    meaning: "bitirmoq",
    definition: "to finish your studies at a university or school",
    pos: "verb",
    level: "B1",
    examples: [
      "She will graduate from university next summer.",
      "He graduated with a degree in economics and moved abroad.",
    ],
    synonyms: ["complete studies"],
    forms: ["graduates", "graduated", "graduating"],
  },
  {
    word: "opportunity",
    meaning: "imkoniyat",
    definition: "a chance to do something useful",
    pos: "noun",
    level: "B1",
    examples: [
      "This job is a great opportunity to learn new skills.",
      "Don't miss the opportunity to travel while you are still young.",
    ],
    synonyms: ["chance"],
    forms: ["opportunities"],
  },
  {
    word: "technology",
    meaning: "texnologiya",
    definition: "machines and methods based on modern science",
    pos: "noun",
    level: "B1",
    examples: [
      "Technology has completely changed the way we work.",
      "The company invests heavily in new technology every year.",
    ],
    synonyms: ["tech"],
    forms: ["technologies"],
  },
  {
    word: "device",
    meaning: "qurilma",
    definition: "a small machine made for a particular job",
    pos: "noun",
    level: "B1",
    examples: [
      "You can open the file on any device, including your phone.",
      "Smart devices are getting cheaper every year.",
    ],
    synonyms: ["gadget"],
    forms: ["devices"],
  },
  {
    word: "application",
    meaning: "ilova, ariza",
    definition: "a computer program, or a formal request for something",
    pos: "noun",
    level: "B1",
    examples: [
      "I downloaded a new application for learning vocabulary.",
      "Your application for the scholarship was accepted.",
    ],
    synonyms: ["app", "formal request"],
    forms: ["applications"],
  },
  {
    word: "feature",
    meaning: "xususiyat, imkoniyat",
    definition: "an important part or quality of something",
    pos: "noun",
    level: "B1",
    examples: [
      "The best feature of this phone is definitely its camera.",
      "The app added a dark mode feature last week.",
    ],
    synonyms: ["characteristic"],
    forms: ["features"],
  },
  {
    word: "internet",
    meaning: "internet",
    definition: "the global network that connects computers",
    pos: "noun",
    level: "B1",
    examples: [
      "I found the recipe on the internet in two minutes.",
      "The internet connection in this building is very slow.",
    ],
    synonyms: ["the web"],
  },
  {
    word: "privacy",
    meaning: "maxfiylik",
    definition: "your right to keep personal things secret",
    pos: "noun",
    level: "B2",
    examples: [
      "Many users worry about their privacy when they use free apps.",
      "Please respect my privacy and don't read my messages.",
    ],
    synonyms: ["confidentiality"],
  },
  {
    word: "security",
    meaning: "xavfsizlik",
    definition: "protection against danger, theft or attack",
    pos: "noun",
    level: "B1",
    examples: [
      "Online banking requires very strong security.",
      "Airport security checked every bag before the flight.",
    ],
    synonyms: ["protection"],
  },
  {
    word: "software",
    meaning: "dasturiy ta'minot",
    definition: "the programs that a computer runs",
    pos: "noun",
    level: "B1",
    examples: [
      "The company develops software for small hospitals.",
      "You should update your software regularly for safety.",
    ],
    synonyms: ["programs"],
  },
  {
    word: "digital",
    meaning: "raqamli",
    definition: "stored or sent as computer data, not on paper",
    pos: "adjective",
    level: "B1",
    examples: [
      "Almost all of our documents are digital now.",
      "She works in digital marketing for a travel company.",
    ],
    synonyms: ["electronic"],
  },
  {
    word: "artificial intelligence",
    meaning: "sun'iy intellekt",
    definition: "computer systems that can do tasks needing human thinking",
    pos: "noun",
    level: "B2",
    examples: [
      "Artificial intelligence can translate long texts in seconds.",
      "Many companies use artificial intelligence to answer customer questions.",
    ],
    synonyms: ["AI"],
  },
  {
    word: "future",
    meaning: "kelajak",
    definition: "the time that will come after now",
    pos: "noun",
    level: "B1",
    examples: [
      "Nobody knows exactly what the future will bring.",
      "In the future, most cars in the city will be electric.",
    ],
    synonyms: ["time ahead"],
  },
  {
    word: "career",
    meaning: "kasb, karyera",
    definition: "the series of jobs a person does over their working life",
    pos: "noun",
    level: "B1",
    examples: [
      "She changed her career completely at the age of thirty.",
      "Learning English can help your career in almost any field.",
    ],
    synonyms: ["professional life"],
    forms: ["careers"],
  },
  {
    word: "goal",
    meaning: "maqsad",
    definition: "something you want to achieve",
    pos: "noun",
    level: "B1",
    examples: [
      "My main goal this year is to speak English fluently.",
      "Write your goals down and review them every month.",
    ],
    synonyms: ["aim"],
    forms: ["goals"],
  },
  {
    word: "dream",
    meaning: "orzu",
    definition: "something you hope for very much",
    pos: "noun",
    level: "B1",
    examples: [
      "Her dream is to open a small cafe near the sea.",
      "Living in the mountains has always been my dream.",
    ],
    synonyms: ["hope"],
    forms: ["dreams", "dreamed", "dreaming"],
  },
  {
    word: "achieve",
    meaning: "erishmoq",
    definition: "to succeed in getting something after effort",
    pos: "verb",
    level: "B1",
    examples: [
      "You can achieve a lot with fifteen minutes of daily practice.",
      "She achieved her main goal in only six months.",
    ],
    synonyms: ["accomplish"],
    forms: ["achieves", "achieved", "achieving"],
  },
  {
    word: "success",
    meaning: "muvaffaqiyat",
    definition: "getting the result you wanted",
    pos: "noun",
    level: "B1",
    examples: [
      "Hard work and patience are the keys to success.",
      "The concert was a huge success and tickets sold out.",
    ],
    synonyms: ["achievement"],
  },
  {
    word: "challenge",
    meaning: "qiyinchilik, sinov",
    definition: "something difficult that tests your ability",
    pos: "noun",
    level: "B1",
    examples: [
      "Learning a new language as an adult is a real challenge.",
      "The team faced many challenges during the first year.",
    ],
    synonyms: ["difficult task"],
    forms: ["challenges", "challenging"],
  },
  {
    word: "effort",
    meaning: "harakat, urinish",
    definition: "the energy you put into doing something",
    pos: "noun",
    level: "B1",
    examples: [
      "With a little more effort you will easily pass the exam.",
      "They made a great effort to finish the report on time.",
    ],
    synonyms: ["hard work"],
    forms: ["efforts"],
  },
  {
    word: "progress",
    meaning: "taraqqiyot, o'sish",
    definition: "movement forward or improvement over time",
    pos: "noun",
    level: "B1",
    examples: [
      "You have made very good progress this month.",
      "Slow progress is still progress, so don't stop now.",
    ],
    synonyms: ["advancement"],
  },
  {
    word: "motivation",
    meaning: "motivatsiya, ruhlanish",
    definition: "the reason or desire that makes you act",
    pos: "noun",
    level: "B2",
    examples: [
      "Her motivation to study comes from her family.",
      "I lost my motivation after the very first failure.",
    ],
    synonyms: ["drive"],
  },
  {
    word: "travel",
    meaning: "sayohat qilmoq",
    definition: "to go from one place to another, usually far away",
    pos: "verb",
    level: "B1",
    examples: [
      "I travel to a different country almost every summer.",
      "They travelled across Europe by train last year.",
    ],
    synonyms: ["journey", "go on a trip"],
    forms: ["travels", "travelled", "traveled", "travelling", "traveling"],
  },
  {
    word: "journey",
    meaning: "safar, yo'l",
    definition: "an act of travelling from one place to another",
    pos: "noun",
    level: "B1",
    examples: [
      "The journey from Tashkent to Samarkand takes about three hours.",
      "Learning a language is a long journey, not a short race.",
    ],
    synonyms: ["trip"],
    forms: ["journeys"],
  },
  {
    word: "destination",
    meaning: "manzil",
    definition: "the place you are travelling to",
    pos: "noun",
    level: "B1",
    examples: [
      "Bali is still the most popular holiday destination for them.",
      "We finally reached our destination after midnight.",
    ],
    synonyms: ["end point"],
    forms: ["destinations"],
  },
  {
    word: "tourist",
    meaning: "sayyoh",
    definition: "a person who visits a place on holiday",
    pos: "noun",
    level: "B1",
    examples: [
      "The old city is full of tourists in the summer months.",
      "A tourist stopped me and asked for directions to the museum.",
    ],
    synonyms: ["visitor"],
    forms: ["tourists"],
  },
  {
    word: "accommodation",
    meaning: "turar joy",
    definition: "a place to live or stay, such as a hotel or flat",
    pos: "noun",
    level: "B2",
    examples: [
      "The price of the tour includes flights and accommodation.",
      "Finding cheap accommodation in the centre is almost impossible.",
    ],
    synonyms: ["lodging"],
  },
  {
    word: "luggage",
    meaning: "yuk, bagaj",
    definition: "the bags you carry when you travel",
    pos: "noun",
    level: "B1",
    examples: [
      "My luggage was lost somewhere between the two airports.",
      "Please do not leave your luggage unattended.",
    ],
    synonyms: ["baggage"],
  },
  {
    word: "route",
    meaning: "yo'nalish",
    definition: "the way you follow to get from one place to another",
    pos: "noun",
    level: "B1",
    examples: [
      "We took the shortest route to the railway station.",
      "The bus route changes on Sundays and holidays.",
    ],
    synonyms: ["path"],
    forms: ["routes"],
  },
  {
    word: "local",
    meaning: "mahalliy",
    definition: "belonging to the area near you",
    pos: "adjective",
    level: "B1",
    examples: [
      "We had dinner in a small local restaurant near the market.",
      "Ask a local guide — they know the quiet streets.",
    ],
    synonyms: ["nearby"],
    forms: ["locals"],
  },
  {
    word: "adventure",
    meaning: "sarguzasht",
    definition: "an exciting and slightly risky experience",
    pos: "noun",
    level: "B1",
    examples: [
      "Our trip to the mountains turned into a real adventure.",
      "He is always looking for adventure in far places.",
    ],
    synonyms: ["exciting experience"],
    forms: ["adventures"],
  },
  {
    word: "explore",
    meaning: "kashf qilmoq, o'rganmoq",
    definition: "to travel through a place, or examine ideas, to learn about them",
    pos: "verb",
    level: "B1",
    examples: [
      "We spent the whole day exploring the old town on foot.",
      "Let's explore other solutions before we decide anything.",
    ],
    synonyms: ["investigate"],
    forms: ["explores", "explored", "exploring"],
  },
  {
    word: "discipline",
    meaning: "intizom",
    definition: "the ability to control yourself and keep working",
    pos: "noun",
    level: "B2",
    examples: [
      "Learning a language on your own requires real discipline.",
      "He has the discipline to train every single morning.",
    ],
    synonyms: ["self-control"],
  },
  {
    word: "productive",
    meaning: "samarali, unumli",
    definition: "getting a lot of useful work done",
    pos: "adjective",
    level: "B2",
    examples: [
      "I feel most productive early in the morning.",
      "It was a productive meeting because we solved three problems.",
    ],
    synonyms: ["efficient"],
  },
  {
    word: "effective",
    meaning: "samarali, ta'sirchan",
    definition: "producing the result you wanted",
    pos: "adjective",
    level: "B2",
    examples: [
      "Short daily lessons are more effective than one long weekly class.",
      "The new teaching method proved very effective.",
    ],
    synonyms: ["successful in result"],
  },
  {
    word: "focus",
    meaning: "diqqatni qaratmoq, diqqat",
    definition: "to give your attention to one particular thing",
    pos: "verb",
    level: "B1",
    examples: [
      "Let's focus on the most important task first.",
      "Turn off your notifications so that you can focus properly.",
    ],
    synonyms: ["concentrate"],
    forms: ["focuses", "focused", "focusing", "focussed"],
  },
  {
    word: "manage",
    meaning: "uddalamoq, boshqarmoq",
    definition: "to control something, or to succeed in doing something difficult",
    pos: "verb",
    level: "B1",
    examples: [
      "She manages a team of ten designers.",
      "I managed to finish the report just before lunch.",
    ],
    synonyms: ["handle"],
    forms: ["manages", "managed", "managing"],
  },
  {
    word: "develop",
    meaning: "rivojlantirmoq",
    definition: "to grow, or to make something bigger and better",
    pos: "verb",
    level: "B1",
    examples: [
      "The company is developing a new application for farmers.",
      "Reading widely helps you develop a bigger vocabulary.",
    ],
    synonyms: ["build up"],
    forms: ["develops", "developed", "developing"],
  },
  {
    word: "decision",
    meaning: "qaror",
    definition: "a choice you make after thinking",
    pos: "noun",
    level: "B1",
    examples: [
      "Moving abroad was the most difficult decision of my life.",
      "We must make a decision before Friday morning.",
    ],
    synonyms: ["conclusion"],
    forms: ["decisions"],
  },
  {
    word: "choice",
    meaning: "tanlov",
    definition: "the act of picking one thing from several",
    pos: "noun",
    level: "B1",
    examples: [
      "You have a choice between two evening courses.",
      "Studying abroad was the best choice I ever made.",
    ],
    synonyms: ["option"],
    forms: ["choices"],
  },
  {
    word: "mistake",
    meaning: "xato",
    definition: "something done wrongly, by accident",
    pos: "noun",
    level: "B1",
    examples: [
      "Everyone makes mistakes when they learn something new.",
      "It was a mistake to leave the house so late.",
    ],
    synonyms: ["error"],
    forms: ["mistakes", "mistaken"],
  },
  {
    word: "solution",
    meaning: "yechim",
    definition: "a way of dealing with a problem",
    pos: "noun",
    level: "B1",
    examples: [
      "We finally found a simple solution to the printing problem.",
      "There is no easy solution to traffic in big cities.",
    ],
    synonyms: ["answer", "fix"],
    forms: ["solutions"],
  },
  {
    word: "money",
    meaning: "pul",
    definition: "coins and notes used to buy things",
    pos: "noun",
    level: "B1",
    examples: [
      "I don't have enough money for a new laptop this month.",
      "He saves a little money every single month.",
    ],
    synonyms: ["cash"],
  },
  {
    word: "income",
    meaning: "daromad",
    definition: "the money you regularly receive from work",
    pos: "noun",
    level: "B2",
    examples: [
      "Their monthly income barely covers all the bills.",
      "He has a second income from teaching online.",
    ],
    synonyms: ["earnings"],
  },
  {
    word: "salary",
    meaning: "maosh",
    definition: "fixed money paid to an employee each month",
    pos: "noun",
    level: "B1",
    examples: [
      "The job offers a good salary and free lunch.",
      "She asked her manager for a higher salary.",
    ],
    synonyms: ["pay"],
    forms: ["salaries"],
  },
  {
    word: "business",
    meaning: "biznes",
    definition: "the activity of buying and selling, or a company",
    pos: "noun",
    level: "B1",
    examples: [
      "They started a small business two years ago.",
      "He is in London on business until Thursday.",
    ],
    synonyms: ["company", "trade"],
    forms: ["businesses"],
  },
  {
    word: "customer",
    meaning: "mijoz",
    definition: "a person who buys goods or services",
    pos: "noun",
    level: "B1",
    examples: [
      "A customer complained about the late delivery.",
      "Good service keeps customers coming back.",
    ],
    synonyms: ["client", "buyer"],
    forms: ["customers"],
  },
  {
    word: "employee",
    meaning: "xodim",
    definition: "a person who is paid to work for a company",
    pos: "noun",
    level: "B1",
    examples: [
      "The company now has over two hundred employees.",
      "Every new employee gets training in the first week.",
    ],
    synonyms: ["worker", "staff member"],
    forms: ["employees"],
  },
  {
    word: "employer",
    meaning: "ish beruvchi",
    definition: "a person or company that pays people to work",
    pos: "noun",
    level: "B1",
    examples: [
      "My employer pays for my English lessons.",
      "A good employer listens to the staff before deciding.",
    ],
    synonyms: ["boss"],
    forms: ["employers"],
  },
  {
    word: "afford",
    meaning: "qurbi yetmoq",
    definition: "to have enough money or time for something",
    pos: "verb",
    level: "B1",
    examples: [
      "I can't afford this laptop right now.",
      "We couldn't afford to eat out every week.",
    ],
    synonyms: ["have enough money for"],
    forms: ["affords", "afforded", "affording"],
  },
  {
    word: "entertainment",
    meaning: "ko'ngilochar dastur",
    definition: "films, music and shows that people enjoy",
    pos: "noun",
    level: "B1",
    examples: [
      "The hotel offers food, drinks and evening entertainment.",
      "Streaming services have changed the entertainment industry.",
    ],
    synonyms: ["amusement"],
  },
  {
    word: "character",
    meaning: "xarakter, qahramon",
    definition: "a person in a story, or someone's personal qualities",
    pos: "noun",
    level: "B1",
    examples: [
      "My favourite character in the book is the old teacher.",
      "Honesty is the strongest part of his character.",
    ],
    synonyms: ["personality"],
    forms: ["characters"],
  },
  {
    word: "story",
    meaning: "hikoya",
    definition: "a description of events, real or invented",
    pos: "noun",
    level: "B1",
    examples: [
      "She told us a funny story about her very first job.",
      "The film is based on a true story from the war.",
    ],
    synonyms: ["tale"],
    forms: ["stories"],
  },
  {
    word: "music",
    meaning: "musiqa",
    definition: "sounds arranged to be pleasant to listen to",
    pos: "noun",
    level: "B1",
    examples: [
      "I listen to quiet music while I work.",
      "Traditional music is still popular at local weddings.",
    ],
    synonyms: ["tunes"],
  },
  {
    word: "performance",
    meaning: "chiqish, ijro, natija",
    definition: "a show in front of an audience, or how well someone does",
    pos: "noun",
    level: "B2",
    examples: [
      "The band's performance lasted almost two hours.",
      "Her performance at work has improved since the training.",
    ],
    synonyms: ["show", "results"],
    forms: ["performances"],
  },
  {
    word: "popular",
    meaning: "mashhur, ommabop",
    definition: "liked by a lot of people",
    pos: "adjective",
    level: "B1",
    examples: [
      "Football is by far the most popular sport here.",
      "This small cafe is popular with students.",
    ],
    synonyms: ["well liked"],
  },
  {
    word: "interesting",
    meaning: "qiziqarli",
    definition: "holding your attention because it is unusual or useful",
    pos: "adjective",
    level: "B1",
    examples: [
      "The lecture was surprisingly interesting.",
      "I read an interesting article about how sleep works.",
    ],
    synonyms: ["engaging"],
  },
  {
    word: "boring",
    meaning: "zerikarli",
    definition: "not interesting at all",
    pos: "adjective",
    level: "B1",
    examples: [
      "The film was so boring that I fell asleep.",
      "Doing exactly the same exercise every day gets boring.",
    ],
    synonyms: ["dull"],
  },
  {
    word: "recommend",
    meaning: "tavsiya qilmoq",
    definition: "to tell someone that something is good and they should try it",
    pos: "verb",
    level: "B1",
    examples: [
      "Can you recommend a good restaurant near the station?",
      "The doctor recommended more exercise and less coffee.",
    ],
    synonyms: ["suggest", "advise"],
    forms: ["recommends", "recommended", "recommending"],
  },
  {
    word: "society",
    meaning: "jamiyat",
    definition: "people living together in an organised community",
    pos: "noun",
    level: "B2",
    examples: [
      "Technology now affects every part of modern society.",
      "In our society, education is valued very highly.",
    ],
    synonyms: ["community"],
    forms: ["societies"],
  },
  {
    word: "opinion",
    meaning: "fikr",
    definition: "what you think or believe about something",
    pos: "noun",
    level: "B1",
    examples: [
      "In my opinion, the price is far too high.",
      "Everyone in the room had a different opinion.",
    ],
    synonyms: ["view"],
    forms: ["opinions"],
  },
  {
    word: "advantage",
    meaning: "afzallik",
    definition: "something that helps you or makes a situation better",
    pos: "noun",
    level: "B1",
    examples: [
      "One advantage of this job is the flexible schedule.",
      "Speaking two languages is a big advantage at work.",
    ],
    synonyms: ["benefit"],
    forms: ["advantages"],
  },
  {
    word: "disadvantage",
    meaning: "kamchilik, salbiy tomon",
    definition: "something that makes a situation worse or harder",
    pos: "noun",
    level: "B2",
    examples: [
      "The main disadvantage of living here is the heavy traffic.",
      "Every method has its own disadvantages.",
    ],
    synonyms: ["drawback"],
    forms: ["disadvantages"],
  },
  {
    word: "reason",
    meaning: "sabab",
    definition: "the cause or explanation for something",
    pos: "noun",
    level: "B1",
    examples: [
      "The main reason for the delay was the bad weather.",
      "Give me one good reason to change my mind.",
    ],
    synonyms: ["cause"],
    forms: ["reasons"],
  },
  {
    word: "however",
    meaning: "biroq, lekin",
    definition: "used to add a contrasting idea",
    pos: "linker",
    level: "B1",
    examples: [
      "The hotel was cheap; however, the rooms were tiny.",
      "I wanted to help. However, I had absolutely no time.",
    ],
    synonyms: ["nevertheless"],
  },
  {
    word: "although",
    meaning: "garchi, -sa ham",
    definition: "used to introduce a contrasting clause",
    pos: "linker",
    level: "B1",
    examples: [
      "Although it was raining hard, we went for a walk.",
      "She passed the exam, although she had studied very little.",
    ],
    synonyms: ["even though"],
  },
  {
    word: "probably",
    meaning: "ehtimol",
    definition: "very likely, but not certain",
    pos: "adverb",
    level: "B1",
    examples: [
      "He is probably still at the office.",
      "It will probably rain again tomorrow afternoon.",
    ],
    synonyms: ["most likely"],
  },
  {
    word: "actually",
    meaning: "aslida",
    definition: "in reality, contrary to what people think",
    pos: "adverb",
    level: "B1",
    examples: [
      "It looks difficult, but it is actually quite simple.",
      "I actually met him last year at a conference.",
    ],
    synonyms: ["in fact"],
  },
  {
    word: "as a result",
    meaning: "natijada",
    definition: "used to show the effect of something",
    pos: "linker",
    level: "B2",
    examples: [
      "He missed the train and, as a result, he was late for the meeting.",
      "Sales fell sharply and, as a result, the shop closed.",
    ],
    synonyms: ["therefore", "consequently"],
  },
  {
    word: "goal-oriented",
    meaning: "maqsadga yo'naltirilgan",
    definition: "focused on reaching clear aims",
    pos: "adjective",
    level: "B2",
    examples: [
      "She is a goal-oriented student who plans every week carefully.",
      "The company is looking for goal-oriented employees.",
    ],
    synonyms: ["ambitious", "focused on results"],
  },
  {
    word: "valuable",
    meaning: "qimmatli, foydali",
    definition: "very useful or worth a lot",
    pos: "adjective",
    level: "B1",
    examples: [
      "Living abroad gave me valuable experience.",
      "Your advice was really valuable, thank you.",
    ],
    synonyms: ["precious", "useful"],
  },
  {
    word: "successful",
    meaning: "muvaffaqiyatli",
    definition: "achieving what you wanted or planned",
    pos: "adjective",
    level: "B1",
    examples: [
      "He is a successful businessman with three shops.",
      "The project was successful despite all the delays.",
    ],
    synonyms: ["prosperous"],
  },
];

/** Barqaror identifikator — localStorage'da so'z shu kalit bilan saqlanadi. */
export function wordId(word: string): string {
  return word.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

export const WORD_BY_ID: ReadonlyMap<string, VocabWord> = new Map(
  WORDS.map((w) => [wordId(w.word), w]),
);

/** So'zning gapda uchraydigan barcha shakllari (asosiy shakl + `forms`). */
export function allForms(w: VocabWord): string[] {
  // Uzunroq shakllar oldin — "improved" ni "improve" dan avval topish uchun.
  return [w.word, ...(w.forms ?? [])].sort((a, b) => b.length - a.length);
}
